model:
  model_name: MLP
  input_dim: 5
  output_dim: 1
  hidden_dim:
  - 10
  - 20
  - 20
  - 5
data:
  date_str: '2024-08-21'
  data_dir: ../Features/
  test_split: 3,4
  scaler_date: '2024-08-21'
  dataset_max: 3000000.0
  split_on: cycle
  features:
  - Energy
  - Capacity
  - Voltage-8
  - Energy-8
  - Power-8
trainer:
  epochs: 5
  save_dir: ./runs/
  exp_name: lfp_sensitivity_custon_arch
  learning_rate: 0.001
  batch_size: 256
  pinn_weight: 0
  pos_enc: false
  GPUs: 2
