
DEFAULT_RESAMPLEING_ALG = "subsample"
DEFAULT_RESAMPLING_PROPORTION = 0.7
DEFAULT_BETA_1 = 0.9
DEFAULT_BETA_2 = 0.999
DEFAULT_MOMENTUM = 0.0
DEFAULT_OPTIMIZER = "adam"
DEFAULT_BATCH_SIZE = 64
DEFAULT_LEARNING_RATE = 1e-3
DEFAULT_EPOCHS = 5
DEFAULT_GPU = 'auto'