model:
  model_name: MLP
  input_dim: 6
  output_dim: 1
  hidden_dim: 256
  num_models: 1
data:
  date_str: '2024-08-21'
  data_dir: ../Features/
  test_split: 3,4
  scaler_date: '2024-08-21'
  dataset_max: 3000000.0
  preprocessing:
  - shifted_NEP
  features:
  - Energy
  - Capacity
  - Voltage-8
  - Energy-8
  - Power-8
trainer:
  epochs: 2
  save_dir: ./runs/
  exp_name: train_pinn_1e6
  learning_rate: 0.001
  batch_size: 1024
  ensemble: true
  pos_enc: false
  initial_est_model: reproduce_lfp
  pinn_weight: 0.1
  resample_alg: bootstrap
