model:
  input_dim: 5
  output_dim: 1
  hidden_dim: 256

data:
  date_str: 2024-08-21
  data_dir: "../Features/"
  test_split: 3,8,15,19,30,31,34,51
  scaler_date: 2024-08-21
  features:
    - "Energy"
    - "Capacity"
    - "Voltage-8"
    - "Energy-8"
    - "Power-8"

trainer:
  epochs: 70
  dataset_max: 
  save_dir: "./runs/"
  exp_name: "lfp_sensitivity_26062025"
  learning_rate: 0.001
  batch_size: 256
  ensemble: True
  num_models: 5
  pos_enc: False
