
model:
  model_name: "MLP"
  input_dim: 5
  output_dim: 1
  hidden_dim: 256
  num_models: 2


data:
  date_str: 2024-08-21
  data_dir: "../Features/"
  test_split: 3,4
  split_on: "cell_num"
  scaler_date: 2024-08-21
  dataset_max: 3e6 #clips data to this size. good for quick training during testing. (make sure test_split is present in data being used)
  features:
    - "Energy"
    - "Capacity"
    - "Voltage-8"
    - "Energy-8"
    - "Power-8"

trainer:
  epochs: 3
  save_dir: "./runs/"
  exp_name: "dummy_test"
  learning_rate: 0.001
  batch_size: 256
  pinn_weight: 0
  optimizer: "SGD"
