model:
  input_dim: 6
  output_dim: 1
  hidden_dim: 256

data:
  date_str: 2024-08-21
  data_dir: "../Features/"
  test_split: 3,8,15,19,30,31,34,51
  scaler_date: 2024-08-21
  features:
    - "Energy"
    - "Capacity"
    - "Voltage-8"
    - "Energy-8"
    - "Power-8"
    - "shifted_NEP"

trainer:
  epochs: 70
  dataset_max: 1e6
  save_dir: "./runs/"
  exp_name: "train_pinn_1e6"
  learning_rate: 0.001
  batch_size: 1024
  ensemble: True
  num_models: 5
  pos_enc: False
  initial_est_model: "reproduce_lfp"