
model:
  model_name: "MLP"
  input_dim: 5
  output_dim: 1
  hidden_dim: 256
  num_models: 1


data:
  date_str: 2024-08-21
  data_dir: "../Features/"
  test_split: 3,4
  split_on: "cell_num"
  scaler_date: 2024-08-21
  dataset_max: 3e6 
  features:
    - "Energy"
    - "Capacity"
    - "Voltage-8"
    - "Energy-8"
    - "Power-8"

trainer:
  epochs: 5
  save_dir: "./runs/"
  exp_name: "og_model_single_ft"
  learning_rate: 0.001
  batch_size: 256
  pinn_weight: 0
  optimizer: "SGD"
  freeze_layers: 0,1
  ckpt_dir: "./runs/og_model_single"
