model:
  model_name: 'MLP'
  input_dim: 6
  output_dim: 1
  hidden_dim: 256
  num_models: 5


data:
  date_str: 2024-08-21
  data_dir: "../Features/"
  test_split: 3,4
  scaler_date: 2024-08-21
  dataset_max: 3e6
  preprocessing:
    - shifted_NEP
  features:
    - "Energy"
    - "Capacity"
    - "Voltage-8"
    - "Energy-8"
    - "Power-8"
    # - "shifted_NEP"

trainer:
  epochs: 2
  save_dir: "./runs/"
  exp_name: "train_pinn_3e6_ensemble_ft"
  learning_rate: 0.001
  batch_size: 1024
  ensemble: True
  pos_enc: False
  initial_est_model: "reproduce_lfp"
  pinn_weight: 0.1
  resample_alg: "bootstrap"
  freeze_layers: 0,1
  ckpt_dir: "./runs/train_pinn_3e6_ensemble"